title: Matthew Vince
url: http://matthewvince.com
description: ''
author:
    name: Matthew Vince
    email: matthew@matthewvince.com
    
pygments: true
permalink: pretty
lsi: true
exclude:
 - Rakefile
 - README.markdown
 - .git